# Generated by Django 5.1.4 on 2024-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=50, unique=True, verbose_name='Kısa Ad')),
                ('original_url', models.URLField(verbose_name='Orijinal URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
